import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


@pytest.mark.network
def test_every_bib_entry_resolves():
    """CLAUDE.md rule 4: every citation must resolve at its registrar."""
    proc = subprocess.run([sys.executable, str(ROOT / "scripts" / "verify_bib.py")],
                          capture_output=True, text=True)
    assert proc.returncode == 0, proc.stdout[-3000:]


def test_bib_is_generated_not_handwritten():
    text = (ROOT / "paper" / "refs.bib").read_text()
    assert text.startswith("% AUTO-GENERATED by scripts/build_bib.py")
    keys = {line.split(",")[0] for line in (ROOT / "paper" / "bib_sources.csv").read_text().splitlines()[1:]}
    for key in keys:
        assert f"{{{key}," in text, f"{key} listed in bib_sources.csv but missing from refs.bib"


SAMPLE_LOG_COLUMNS = ("toi,tic,decision,reason,stage,timestamp_utc,git_commit,snapshot_date,"
                      "sectors_all,sectors_early,sectors_later,product_files,lc_listing_date,"
                      "data_release,download_date,truth_tier,truth_period,truth_source,"
                      "b2_eligible,b2_reason")


def test_sample_log_header():
    """Columns pre-registered in docs/sample_definition.md, Section 7."""
    header = (ROOT / "data" / "sample_log.csv").read_text().splitlines()[0]
    assert header == SAMPLE_LOG_COLUMNS
