import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


@pytest.mark.network
def test_every_bib_entry_resolves():
    """CLAUDE.md rule 4: every citation must resolve at its registrar."""
    proc = subprocess.run([sys.executable, str(ROOT / "scripts" / "verify_bib.py")],
                          capture_output=True, text=True)
    assert proc.returncode == 0, proc.stdout[-3000:]


def test_bib_is_generated_not_handwritten():
    text = (ROOT / "paper" / "refs.bib").read_text()
    assert text.startswith("% AUTO-GENERATED by scripts/build_bib.py")
    keys = {line.split(",")[0] for line in (ROOT / "paper" / "bib_sources.csv").read_text().splitlines()[1:]}
    for key in keys:
        assert f"{{{key}," in text, f"{key} listed in bib_sources.csv but missing from refs.bib"


def test_sample_log_header():
    header = (ROOT / "data" / "sample_log.csv").read_text().splitlines()[0]
    assert header == "target,decision,reason,stage,timestamp_utc,git_commit"
