"""Build paper/refs.bib from paper/bib_sources.csv.

Every entry is fetched from its registrar (doi.org content negotiation for
DOIs, the arXiv API for preprints). Nothing is typed by hand, so a citation
can only exist if its identifier resolves (CLAUDE.md rule 4).
"""

import csv
import json
import re
import sys
import time
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "paper" / "bib_sources.csv"
OUT_BIB = ROOT / "paper" / "refs.bib"
OUT_META = ROOT / "data" / "cache" / "lit" / "bib_metadata.json"
UA = {"User-Agent": "exogargantua-bibcheck (mailto:cybrobasics@gmail.com)"}
ATOM = {"a": "http://www.w3.org/2005/Atom", "x": "http://arxiv.org/schemas/atom"}


def _get(url, headers=None, tries=4):
    hdr = dict(UA, **(headers or {}))
    for i in range(tries):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=hdr), timeout=60) as r:
                return r.read().decode("utf-8")
        except Exception:  # network hiccup: back off and retry
            if i == tries - 1:
                raise
            time.sleep(3 * (i + 1))


def fetch_doi(doi):
    bib = _get(f"https://doi.org/{doi}", {"Accept": "application/x-bibtex; charset=utf-8"})
    m = re.search(r"title\s*=\s*\{(.+?)\},?\s*\n", bib, flags=re.S)
    title = m.group(1) if m else ""
    return bib.strip(), title


def fetch_arxiv(aid):
    xml = _get(f"http://export.arxiv.org/api/query?id_list={aid}")
    e = ET.fromstring(xml).find("a:entry", ATOM)
    title = " ".join(e.find("a:title", ATOM).text.split())
    authors = " and ".join(a.find("a:name", ATOM).text for a in e.findall("a:author", ATOM))
    year = e.find("a:published", ATOM).text[:4]
    bib = (
        "@misc{KEY,\n"
        f"  title = {{{title}}},\n"
        f"  author = {{{authors}}},\n"
        f"  year = {{{year}}},\n"
        f"  eprint = {{{aid}}},\n"
        "  archivePrefix = {arXiv},\n"
        f"  url = {{https://arxiv.org/abs/{aid}}}\n"
        "}"
    )
    return bib, title


def main():
    entries, meta = [], {}
    with open(SOURCES) as fh:
        rows = list(csv.DictReader(fh))
    for row in rows:
        key, kind, ident = row["key"], row["id_type"], row["id"]
        bib, title = fetch_doi(ident) if kind == "doi" else fetch_arxiv(ident)
        bib = re.sub(r"^@(\w+)\{[^,]*,", lambda m: f"@{m.group(1)}{{{key},", bib, count=1)
        bib = bib.replace("@misc{KEY,", f"@misc{{{key},")
        entries.append(bib)
        meta[key] = {"id_type": kind, "id": ident, "title": title, "topic": row["topic"]}
        print(f"ok  {key:22s} {kind:5s} {ident}  | {title[:70]}")
        time.sleep(0.5)
    OUT_BIB.write_text("% AUTO-GENERATED by scripts/build_bib.py -- do not edit by hand\n\n" + "\n\n".join(entries) + "\n")
    OUT_META.parent.mkdir(parents=True, exist_ok=True)
    OUT_META.write_text(json.dumps(meta, indent=1))
    print(f"wrote {len(entries)} entries to {OUT_BIB.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
